### ISSUE TITLE
Latest-5-commits-peer-to-peer-code-review

### ISSUE THREAD

**Issue by ITurres** [henask12/Portfolio#5]
Hi @henask12,

### Suggested Changes ♻️:

- If there is a commonly used {property: value} within the same stylesheet,
  consider targeting all the classes/id/etc that use it, and apply them all together.

e.g.

```css
.class_1,
.class_2,
#id_1 {
  font-size: 2rem;
}
```

- consider installing a Code-Formatter in order to keep your code well formatted before adding (git add) the file to the stage.

   - e.g.: Prettier

---

- ##### NOTE: members of the team will leave their review comments on the thread.

**Comment by mm-pazouki** [comment]
index.html
Line 334
- [ ] It is better to remove unused attributes and move CSS styles to the CSS file.

style.css
- [ ] It is better to use % to make a good style than the pixel.

**Comment by sergio-usma** [comment]
Hi! @henask12 I have this kind suggestions for your code:
![Screenshot from 2023-05-04 09-33-23](https://user-images.githubusercontent.com/126805818/236242420-8b930728-cac4-460a-b83e-7b78d97725fa.png)
![Screenshot from 2023-05-04 09-34-09](https://user-images.githubusercontent.com/126805818/236242433-5281ab52-2c6d-49cb-88ee-dce129896f4a.png)
![Screenshot from 2023-05-04 09-34-59](https://user-images.githubusercontent.com/126805818/236242441-2c7b9cea-752e-436d-8c3a-55203c6c28fd.png)
